theme:
  active_themes: [unm]

themes:
  unm:
    internal_css:
      - /styles/unm/*.css
    variables:
      light:
        font:
          content: '"Gotham A","Gotham B","Gotham Pro","Gotham","Helvetica Neue",Helvetica,Arial,sans-serif'
          header: '"Vitesse A","Vitesse B","Vitesse",Cambria,Rockwell,"Times New Roman",serif'
          ui: '"Helvetica Neue",Helvetica,Arial,sans-serif'
        theme:
          neutral: '#63666a'
          accent: '#ba0c2f'
          highlight: '#8a387c'
        cue:
          information: '#007a86'
          safe: '#a8aa19'
          warning: '#8a387c'
          danger: '#ed8b00'

user_sources:
  cas:
    providers:
      netid:
        name: UNM NetID
        active: true
        version: CAS_VERSION_2_0
        server: login.unm.edu
        port: 443
        context: cas
        setnocasservervalidation: true
        fixhttpsproblems: true
