unm:
  loboalert_ttl: 3600
  block_unknown_netids: false
  known_netids: []

theme:
  active_themes: [unm]
  timezone: America/Denver

themes:
  unm:
    external_css:
      unm_fonts: https://cloud.typography.com/7254094/6839152/css/fonts.css
    internal_css:
      unm: /styles_unm/*.css
    variables:
      light:
        line-length: 45em
        font:
          content: '"Gotham A","Gotham B","Gotham Pro","Gotham","Helvetica Neue",Helvetica,Arial,sans-serif'
          header: '"Vitesse A","Vitesse B","Vitesse",Cambria,Rockwell,"Times New Roman",serif'
          ui: '"Helvetica Neue",Helvetica,Arial,sans-serif'
        theme:
          neutral: '#63666a'
          accent: '#a7a8aa'
          highlight: '#ba0c2f'
        cue:
          information: '#007a86'
          safe: '#43A047'
          warning: '#FFA000'
          danger: '#F4511E'

user_sources:
  cas:
    providers:
      netid:
        name: UNM NetID
        active: true
        version: CAS_VERSION_2_0
        server: login.unm.edu
        port: 443
        context: cas
        setnocasservervalidation: true
        fixhttpsproblems: true
